/**
 * Language.
 *
 * English, French, Spanish for now. UI strings live in the dictionary below;
 * `t(key)` returns the current language, falling back to English, then the key
 * itself. The chosen language is remembered across launches.
 *
 * Note: this translates the app's *chrome*. Scripture text depends on which
 * Bible translation is loaded (FR/ES translations are a data import), and AI
 * explanations follow the language only when a real, language-aware AI provider
 * is configured — the offline mock is English.
 */

import {
  createContext,
  type ReactNode,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useState,
} from 'react';

import * as storage from '@/state/storage';

export type Locale = 'en' | 'fr' | 'es';
export const LOCALES: { value: Locale; label: string }[] = [
  { value: 'en', label: 'English' },
  { value: 'fr', label: 'Français' },
  { value: 'es', label: 'Español' },
];

/** Which Bible translation to read in each language. */
export const TRANSLATION_FOR: Record<Locale, string> = {
  en: 'WEB',
  fr: 'OST',
  es: 'RVR',
};

const KEY = 'selah.locale';

type Dict = Record<string, string>;

const STRINGS: Record<Locale, Dict> = {
  en: {
    'nav.today': 'Today',
    'nav.reader': 'Reader',
    'nav.study': 'Study',
    'nav.notes': 'Notes',
    'nav.you': 'You',
    'nav.library': 'Library',
    'nav.account': 'Account',
    'brand.tagline': 'Bible Study',
    'today.morning': 'Good morning',
    'today.afternoon': 'Good afternoon',
    'today.evening': 'Good evening',
    'today.subtitle': 'Take a moment with one verse.',
    'today.reflect': 'Reflect on this verse',
    'today.openReader': 'Open the Reader',
    'today.finding': "Finding today's verse…",
    'today.signinPre': 'Reading never needs an account. ',
    'today.signinLink': 'Sign in',
    'today.signinPost': ' to keep notes and favorites.',
    'reader.immersion': 'Immersion',
    'reader.study': 'Study',
    'reader.ot': 'Old Testament',
    'reader.nt': 'New Testament',
    'reader.chapter': 'Chapter',
    'inspector.title': 'Context Inspector',
    'inspector.emptyTitle': 'Explore the text',
    'inspector.emptyMsg':
      'Tap any verse to see its meaning, context, how to live it, and related passages — explained by AI.',
    'settings.language': 'Language',
    'settings.appearance': 'Appearance',
    'study.subtitle': 'Ask about any verse.',
    'study.placeholder': 'John 3:16, or a phrase like "do not be anxious"',
    'study.explain': 'Explain',
    'study.results': '{n} results for "{q}"',
    'study.noMatch':
      'Nothing in the loaded chapters matches that. The sample set covers Genesis 1, Psalm 23 and 100, John 3, 1 Corinthians 13, and Philippians 4.',
    'notes.subtitle': 'What you noticed, in your own words.',
    'notes.placeholder': 'What stood out to you?',
    'notes.save': 'Save note',
    'notes.emptyTitle': 'Nothing written yet',
    'notes.emptyMsg': 'Read a verse, then come back and write one honest line about it.',
    'notes.signin': 'Notes sync to your account so they survive a new phone. Sign in to start writing.',
    'notes.delete': 'Delete',
    'tone.plain': 'Plain',
    'tone.devotional': 'Devotional',
    'tone.scholarly': 'Scholarly',
    'tone.kids': 'For kids',
    'common.somethingWrong': 'Something went wrong.',
    'common.tryAgain': 'Try again',
    'common.cancel': 'Cancel',
    'state.loading': 'Loading…',
    'state.generatingTitle': 'Sitting with the verse…',
    'state.generatingBody':
      'Reading it in context, and how it connects. A few seconds the first time — after that it is instant.',
    'state.offlineTitle': "Can't reach the server",
    'state.brokeTitle': 'Something broke',
    'state.offlineHintPre': 'Start the API with',
    'state.offlineHintPost': 'in apps/api, then try again.',
    'state.signinTitle': 'Keep this with you',
    'explain.meaning': 'What it means',
    'explain.context': 'Context',
    'explain.application': 'Living it today',
    'explain.readAlongside': 'Read alongside',
    'explain.saved': 'Saved',
    'explain.disclaimer':
      'Generated by AI to help you study — not a substitute for the text itself, your own reading, or your community.',
    'verse.title': 'Explanation',
    'verse.save': 'Save verse',
    'verse.regenerate': 'Regenerate',
    'verse.savedTitle': 'Saved',
    'verse.savedBody': '{ref} is in your saved verses.',
    'verse.couldNotSave': 'Could not save',
    'verse.notLoadedTitle': 'Not loaded yet',
    'verse.notLoadedBody': '{ref} is not in the sample data set yet.',
    'verse.couldNotExplain': 'Could not explain that verse.',
    'chapter.inShort': 'In short',
    'chapter.summarise': 'Summarise this chapter',
    'chapter.verses': '{n} verses',
    'chapter.tapHint': 'Tap a verse to explain or save it.',
    'chapter.explain': 'Explain',
    'chapter.save': 'Save',
    'chapter.couldNotSummarise': 'Could not summarise',
    'profile.signout': 'Sign out',
    'profile.signoutTitle': 'Sign out?',
    'profile.signoutBody': 'Your notes stay saved to your account.',
    'profile.notSignedIn': 'Not signed in',
    'profile.notSignedInBody': 'Reading works without an account. Notes and saved verses need one.',
    'profile.signInCta': 'Sign in or create an account',
    'profile.premiumLabel': 'Selah Premium',
    'profile.premiumTitle': 'Unlimited explanations',
    'profile.premiumBody':
      'Every voice, licensed modern translations, offline chapters, and no daily cap.',
    'profile.comingSoon': 'Coming soon',
    'profile.savedVerses': 'Saved verses',
    'profile.nothingSavedTitle': 'Nothing saved yet',
    'profile.nothingSavedBody':
      'Tap the bookmark on any verse while reading and it will show up here.',
    'profile.about': 'About',
    'signin.createTitle': 'Create an account',
    'signin.welcomeTitle': 'Welcome back',
    'signin.createSubtitle': 'So your notes and saved verses follow you.',
    'signin.welcomeSubtitle': 'Sign in to reach your notes and saved verses.',
    'signin.name': 'Your name',
    'signin.email': 'Email',
    'signin.password': 'Password (at least 8 characters)',
    'signin.createBtn': 'Create account',
    'signin.signInBtn': 'Sign in',
    'signin.haveAccount': 'I already have an account',
    'signin.newHere': "I'm new here",
    'today.votd': 'Verse of the day',
    'profile.devBuild': 'development build',
    'profile.scriptureNote': 'Public-domain scripture: WEB, Ostervald (FR), Reina-Valera (ES).',
  },
  fr: {
    'nav.today': "Aujourd'hui",
    'nav.reader': 'Lecture',
    'nav.study': 'Étude',
    'nav.notes': 'Notes',
    'nav.you': 'Vous',
    'nav.library': 'Bibliothèque',
    'nav.account': 'Compte',
    'brand.tagline': 'Étude biblique',
    'today.morning': 'Bonjour',
    'today.afternoon': 'Bon après-midi',
    'today.evening': 'Bonsoir',
    'today.subtitle': 'Prenez un instant avec un verset.',
    'today.reflect': 'Méditer ce verset',
    'today.openReader': 'Ouvrir la lecture',
    'today.finding': "Recherche du verset du jour…",
    'today.signinPre': 'La lecture ne demande aucun compte. ',
    'today.signinLink': 'Se connecter',
    'today.signinPost': ' pour garder notes et favoris.',
    'reader.immersion': 'Immersion',
    'reader.study': 'Étude',
    'reader.ot': 'Ancien Testament',
    'reader.nt': 'Nouveau Testament',
    'reader.chapter': 'Chapitre',
    'inspector.title': 'Inspecteur de contexte',
    'inspector.emptyTitle': 'Explorer le texte',
    'inspector.emptyMsg':
      "Touchez un verset pour voir son sens, son contexte, comment le vivre, et des passages liés — expliqués par l'IA.",
    'settings.language': 'Langue',
    'settings.appearance': 'Apparence',
    'study.subtitle': 'Posez une question sur un verset.',
    'study.placeholder': 'Jean 3:16, ou une phrase comme « ne vous inquiétez pas »',
    'study.explain': 'Expliquer',
    'study.results': '{n} résultats pour « {q} »',
    'study.noMatch':
      "Aucun résultat dans les chapitres chargés. L'échantillon couvre Genèse 1, Psaumes 23 et 100, Jean 3, 1 Corinthiens 13 et Philippiens 4.",
    'notes.subtitle': 'Ce que vous avez remarqué, avec vos mots.',
    'notes.placeholder': "Qu'est-ce qui vous a marqué ?",
    'notes.save': 'Enregistrer la note',
    'notes.emptyTitle': 'Rien écrit pour le moment',
    'notes.emptyMsg': 'Lisez un verset, puis revenez écrire une ligne sincère à son sujet.',
    'notes.signin':
      'Les notes sont liées à votre compte pour survivre à un nouveau téléphone. Connectez-vous pour commencer.',
    'notes.delete': 'Supprimer',
    'tone.plain': 'Simple',
    'tone.devotional': 'Dévotionnel',
    'tone.scholarly': 'Savant',
    'tone.kids': 'Pour enfants',
    'common.somethingWrong': "Une erreur s'est produite.",
    'common.tryAgain': 'Réessayer',
    'common.cancel': 'Annuler',
    'state.loading': 'Chargement…',
    'state.generatingTitle': 'Méditation du verset…',
    'state.generatingBody':
      "On le lit dans son contexte et ses liens. Quelques secondes la première fois — ensuite c'est instantané.",
    'state.offlineTitle': 'Serveur injoignable',
    'state.brokeTitle': 'Une erreur est survenue',
    'state.offlineHintPre': "Démarrez l'API avec",
    'state.offlineHintPost': 'dans apps/api, puis réessayez.',
    'state.signinTitle': 'Gardez ceci avec vous',
    'explain.meaning': 'Ce que cela signifie',
    'explain.context': 'Contexte',
    'explain.application': 'Le vivre aujourd’hui',
    'explain.readAlongside': 'À lire aussi',
    'explain.saved': 'Enregistré',
    'explain.disclaimer':
      "Généré par l'IA pour vous aider à étudier — ne remplace pas le texte lui-même, votre lecture, ni votre communauté.",
    'verse.title': 'Explication',
    'verse.save': 'Enregistrer le verset',
    'verse.regenerate': 'Régénérer',
    'verse.savedTitle': 'Enregistré',
    'verse.savedBody': '{ref} est dans vos versets enregistrés.',
    'verse.couldNotSave': 'Enregistrement impossible',
    'verse.notLoadedTitle': 'Pas encore chargé',
    'verse.notLoadedBody': "{ref} n'est pas encore dans l'échantillon.",
    'verse.couldNotExplain': "Impossible d'expliquer ce verset.",
    'chapter.inShort': 'En bref',
    'chapter.summarise': 'Résumer ce chapitre',
    'chapter.verses': '{n} versets',
    'chapter.tapHint': 'Touchez un verset pour l’expliquer ou l’enregistrer.',
    'chapter.explain': 'Expliquer',
    'chapter.save': 'Enregistrer',
    'chapter.couldNotSummarise': 'Résumé impossible',
    'profile.signout': 'Se déconnecter',
    'profile.signoutTitle': 'Se déconnecter ?',
    'profile.signoutBody': 'Vos notes restent liées à votre compte.',
    'profile.notSignedIn': 'Non connecté',
    'profile.notSignedInBody': 'La lecture ne demande aucun compte. Les notes et favoris, oui.',
    'profile.signInCta': 'Se connecter ou créer un compte',
    'profile.premiumLabel': 'Selah Premium',
    'profile.premiumTitle': 'Explications illimitées',
    'profile.premiumBody':
      'Toutes les voix, des traductions modernes sous licence, des chapitres hors ligne, sans limite quotidienne.',
    'profile.comingSoon': 'Bientôt disponible',
    'profile.savedVerses': 'Versets enregistrés',
    'profile.nothingSavedTitle': 'Rien d’enregistré',
    'profile.nothingSavedBody':
      'Touchez le signet sur un verset pendant la lecture et il apparaîtra ici.',
    'profile.about': 'À propos',
    'signin.createTitle': 'Créer un compte',
    'signin.welcomeTitle': 'Bon retour',
    'signin.createSubtitle': 'Pour que vos notes et favoris vous suivent.',
    'signin.welcomeSubtitle': 'Connectez-vous pour retrouver vos notes et favoris.',
    'signin.name': 'Votre nom',
    'signin.email': 'E-mail',
    'signin.password': 'Mot de passe (au moins 8 caractères)',
    'signin.createBtn': 'Créer le compte',
    'signin.signInBtn': 'Se connecter',
    'signin.haveAccount': "J'ai déjà un compte",
    'signin.newHere': 'Je suis nouveau',
    'today.votd': 'Verset du jour',
    'profile.devBuild': 'version de développement',
    'profile.scriptureNote': 'Écritures du domaine public : WEB, Ostervald (FR), Reina-Valera (ES).',
  },
  es: {
    'nav.today': 'Hoy',
    'nav.reader': 'Lectura',
    'nav.study': 'Estudio',
    'nav.notes': 'Notas',
    'nav.you': 'Tú',
    'nav.library': 'Biblioteca',
    'nav.account': 'Cuenta',
    'brand.tagline': 'Estudio bíblico',
    'today.morning': 'Buenos días',
    'today.afternoon': 'Buenas tardes',
    'today.evening': 'Buenas noches',
    'today.subtitle': 'Tómate un momento con un versículo.',
    'today.reflect': 'Reflexionar en este versículo',
    'today.openReader': 'Abrir la lectura',
    'today.finding': 'Buscando el versículo de hoy…',
    'today.signinPre': 'La lectura no requiere una cuenta. ',
    'today.signinLink': 'Iniciar sesión',
    'today.signinPost': ' para guardar notas y favoritos.',
    'reader.immersion': 'Inmersión',
    'reader.study': 'Estudio',
    'reader.ot': 'Antiguo Testamento',
    'reader.nt': 'Nuevo Testamento',
    'reader.chapter': 'Capítulo',
    'inspector.title': 'Inspector de contexto',
    'inspector.emptyTitle': 'Explora el texto',
    'inspector.emptyMsg':
      'Toca cualquier versículo para ver su significado, contexto, cómo vivirlo y pasajes relacionados — explicados por IA.',
    'settings.language': 'Idioma',
    'settings.appearance': 'Apariencia',
    'study.subtitle': 'Pregunta sobre cualquier versículo.',
    'study.placeholder': 'Juan 3:16, o una frase como «no se angustien»',
    'study.explain': 'Explicar',
    'study.results': '{n} resultados para «{q}»',
    'study.noMatch':
      'Nada en los capítulos cargados coincide. La muestra cubre Génesis 1, Salmos 23 y 100, Juan 3, 1 Corintios 13 y Filipenses 4.',
    'notes.subtitle': 'Lo que notaste, con tus palabras.',
    'notes.placeholder': '¿Qué te llamó la atención?',
    'notes.save': 'Guardar nota',
    'notes.emptyTitle': 'Nada escrito aún',
    'notes.emptyMsg': 'Lee un versículo y luego vuelve a escribir una línea sincera sobre él.',
    'notes.signin':
      'Las notas se guardan en tu cuenta para sobrevivir a un teléfono nuevo. Inicia sesión para empezar.',
    'notes.delete': 'Eliminar',
    'tone.plain': 'Sencillo',
    'tone.devotional': 'Devocional',
    'tone.scholarly': 'Académico',
    'tone.kids': 'Para niños',
    'common.somethingWrong': 'Algo salió mal.',
    'common.tryAgain': 'Intentar de nuevo',
    'common.cancel': 'Cancelar',
    'state.loading': 'Cargando…',
    'state.generatingTitle': 'Reflexionando el versículo…',
    'state.generatingBody':
      'Se lee en su contexto y sus conexiones. Unos segundos la primera vez — después es instantáneo.',
    'state.offlineTitle': 'No se puede conectar al servidor',
    'state.brokeTitle': 'Algo falló',
    'state.offlineHintPre': 'Inicia la API con',
    'state.offlineHintPost': 'en apps/api y vuelve a intentar.',
    'state.signinTitle': 'Guárdalo contigo',
    'explain.meaning': 'Qué significa',
    'explain.context': 'Contexto',
    'explain.application': 'Vivirlo hoy',
    'explain.readAlongside': 'Leer junto a',
    'explain.saved': 'Guardado',
    'explain.disclaimer':
      'Generado por IA para ayudarte a estudiar — no sustituye al texto mismo, tu propia lectura ni tu comunidad.',
    'verse.title': 'Explicación',
    'verse.save': 'Guardar versículo',
    'verse.regenerate': 'Regenerar',
    'verse.savedTitle': 'Guardado',
    'verse.savedBody': '{ref} está en tus versículos guardados.',
    'verse.couldNotSave': 'No se pudo guardar',
    'verse.notLoadedTitle': 'Aún no cargado',
    'verse.notLoadedBody': '{ref} todavía no está en la muestra.',
    'verse.couldNotExplain': 'No se pudo explicar ese versículo.',
    'chapter.inShort': 'En resumen',
    'chapter.summarise': 'Resumir este capítulo',
    'chapter.verses': '{n} versículos',
    'chapter.tapHint': 'Toca un versículo para explicarlo o guardarlo.',
    'chapter.explain': 'Explicar',
    'chapter.save': 'Guardar',
    'chapter.couldNotSummarise': 'No se pudo resumir',
    'profile.signout': 'Cerrar sesión',
    'profile.signoutTitle': '¿Cerrar sesión?',
    'profile.signoutBody': 'Tus notas siguen guardadas en tu cuenta.',
    'profile.notSignedIn': 'Sin sesión iniciada',
    'profile.notSignedInBody':
      'La lectura funciona sin cuenta. Las notas y los versículos guardados la necesitan.',
    'profile.signInCta': 'Inicia sesión o crea una cuenta',
    'profile.premiumLabel': 'Selah Premium',
    'profile.premiumTitle': 'Explicaciones ilimitadas',
    'profile.premiumBody':
      'Todas las voces, traducciones modernas con licencia, capítulos sin conexión y sin límite diario.',
    'profile.comingSoon': 'Próximamente',
    'profile.savedVerses': 'Versículos guardados',
    'profile.nothingSavedTitle': 'Nada guardado aún',
    'profile.nothingSavedBody':
      'Toca el marcador en cualquier versículo mientras lees y aparecerá aquí.',
    'profile.about': 'Acerca de',
    'signin.createTitle': 'Crear una cuenta',
    'signin.welcomeTitle': 'Bienvenido de nuevo',
    'signin.createSubtitle': 'Para que tus notas y favoritos te acompañen.',
    'signin.welcomeSubtitle': 'Inicia sesión para acceder a tus notas y versículos guardados.',
    'signin.name': 'Tu nombre',
    'signin.email': 'Correo electrónico',
    'signin.password': 'Contraseña (al menos 8 caracteres)',
    'signin.createBtn': 'Crear cuenta',
    'signin.signInBtn': 'Iniciar sesión',
    'signin.haveAccount': 'Ya tengo una cuenta',
    'signin.newHere': 'Soy nuevo aquí',
    'today.votd': 'Versículo del día',
    'profile.devBuild': 'compilación de desarrollo',
    'profile.scriptureNote': 'Escrituras de dominio público: WEB, Ostervald (FR), Reina-Valera (ES).',
  },
};

function detectLocale(): Locale {
  try {
    const nav = (globalThis as { navigator?: { language?: string } }).navigator;
    const two = (nav?.language ?? 'en').slice(0, 2).toLowerCase();
    return two === 'fr' ? 'fr' : two === 'es' ? 'es' : 'en';
  } catch {
    return 'en';
  }
}

interface LocaleContextValue {
  locale: Locale;
  setLocale: (locale: Locale) => void;
  t: (key: string) => string;
}

const LocaleContext = createContext<LocaleContextValue | null>(null);

export function LocaleProvider({ children }: { children: ReactNode }) {
  const [locale, setLocaleState] = useState<Locale>('en');

  useEffect(() => {
    let active = true;
    (async () => {
      const stored = await storage.getItem(KEY);
      if (!active) return;
      if (stored === 'en' || stored === 'fr' || stored === 'es') setLocaleState(stored);
      else setLocaleState(detectLocale());
    })();
    return () => {
      active = false;
    };
  }, []);

  const setLocale = useCallback((next: Locale) => {
    setLocaleState(next);
    void storage.setItem(KEY, next);
  }, []);

  const t = useCallback(
    (key: string) => STRINGS[locale][key] ?? STRINGS.en[key] ?? key,
    [locale],
  );

  const value = useMemo<LocaleContextValue>(() => ({ locale, setLocale, t }), [locale, setLocale, t]);
  return <LocaleContext.Provider value={value}>{children}</LocaleContext.Provider>;
}

export function useLocale(): LocaleContextValue {
  const context = useContext(LocaleContext);
  if (!context) throw new Error('useLocale must be used inside <LocaleProvider>.');
  return context;
}
